# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-github-action-token-rotator
  description: A Terraform module to deploy the GitHub Action Runner Token Rotator lambda function
  homepage: https://cloudposse.com/accelerate
  topics: ""





